# global robot configuration and details

robot_config:
    # command rate limits for the FrankaHW controllers
    # Default limits pulled from https://frankaemika.github.io/docs/control_parameters.html
    joint_limits:
        panda_joint1:
            has_position_limits: true
            min_position: -2.8973
            max_position: 2.8973
            has_velocity_limits: true
            max_velocity: 0.5 #2.1750
            has_acceleration_limits: true
            max_acceleration: 15.0
            has_jerk_limits: true
            max_jerk: 7500.0
            has_effort_limits: true
            max_effort: 3.0  #87.0
        panda_joint2:
            has_position_limits: true
            min_position: -1.7628
            max_position: 1.7628
            has_velocity_limits: true
            max_velocity: 0.5 #2.1750
            has_acceleration_limits: true
            max_acceleration: 7.5
            has_jerk_limits: true
            max_jerk: 3750.0
            has_effort_limits: true
            max_effort: 3.0 #87.0
        panda_joint3:
            has_position_limits: true
            min_position: -2.8973
            max_position: 2.8973
            has_velocity_limits: true
            max_velocity: 0.5 #2.1750
            has_acceleration_limits: true
            max_acceleration: 10.0
            has_jerk_limits: true
            max_jerk: 5000.0
            has_effort_limits: true
            max_effort: 3.0 #87.0
        panda_joint4:
            has_position_limits: true
            min_position: -3.0718
            max_position: -0.0698
            has_velocity_limits: true
            max_velocity: 2.0 #0.3 #2.1750  
            has_acceleration_limits: true
            max_acceleration: 12.5
            has_jerk_limits: true
            max_jerk: 6250.0
            has_effort_limits: true
            max_effort: 3.0 #87.0
        panda_joint5:
            has_position_limits: true
            min_position: -2.8973
            max_position: 2.8973
            has_velocity_limits: true
            max_velocity:  0.5 # 2.0# 2.6100
            has_acceleration_limits: true
            max_acceleration: 15.0
            has_jerk_limits: true
            max_jerk: 7500.0
            has_effort_limits: true
            max_effort: 1.0 #12.0
        panda_joint6:
            has_position_limits: true
            min_position: -0.0175
            max_position: 3.7525
            has_velocity_limits: true
            max_velocity: 2.0 #0.5 #2.6100  
            has_acceleration_limits: true
            max_acceleration: 20.0 #0.1 
            has_jerk_limits: true
            max_jerk: 10000.0
            has_effort_limits: true
            max_effort: 7.5 #12.0
        panda_joint7:
            has_position_limits: true
            min_position: -2.8973
            max_position: 2.8973
            has_velocity_limits: true
            max_velocity: 0.5 # 2.6100
            has_acceleration_limits: true
            max_acceleration: 20.0
            has_jerk_limits: true
            max_jerk: 10000.0
            has_effort_limits: true
            max_effort: 1.0 #12.0
    joint_names:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    arm_id: panda
    # Activate rate limiter? [true|false]
    rate_limiting: true # at the FCI level
    joint_limit_warning_threshold: 0.3 #0.1 # [rad]
    # Cutoff frequency of the low-pass filter. Set to >= 1000 to deactivate.
    cutoff_frequency: 100
    # Internal controller for motion generators [joint_impedance|cartesian_impedance]
    internal_controller: joint_impedance

    neutral_pose:
        panda_joint1: -0.017792060227770554 
        panda_joint2: -0.7601235411041661  
        panda_joint3: 0.019782607023391807 
        panda_joint4: -2.342050140544315 
        panda_joint5: 0.029840531355804868 
        panda_joint6: 1.5411935298621688 
        panda_joint7: 0.7534486589746342 

    # limits loaded by franka_interface/robot_params
    # best to leave these as defaults i think...
    # can change command rate limits above!
    joint_config:
        joint_acceleration_limit:
            panda_joint1: 15.0 # rad / sec^2
            panda_joint2: 7.5  # rad / sec^2
            panda_joint3: 10.0 # rad / sec^2
            panda_joint4: 12.5 # rad / sec^2
            panda_joint5: 15.0 # rad / sec^2
            panda_joint6: 20.0 # rad / sec^2
            panda_joint7: 20.0 # rad / sec^2
            # panda_finger_joint1: 12.0 # rad / sec^2
            # panda_finger_joint2: 12.0 # rad / sec^2

        joint_velocity_limit:
            panda_joint1: 2.1750 #0.01 #1  # rad / sec
            panda_joint2: 2.1750 #0.01 #1  # rad / sec
            panda_joint3: 2.1750 #0.01 #1  # rad / sec
            panda_joint4: 2.1750 #0.01 #1  # rad / sec
            panda_joint5: 2.6100 #0.01 #1.3  # rad / sec
            panda_joint6: 2.6100 #0.01 #1.3  # rad / sec
            panda_joint7: 2.6100 #0.01 #1.3  # rad / sec
            # panda_finger_joint1: 2.0 # rad / sec
            # panda_finger_joint2: 2.0 # rad / sec

        joint_position_limit:
            lower: 
                panda_joint1: -2.8973 # rad
                panda_joint2: -1.7628 # rad
                panda_joint3: -2.8973 # rad
                panda_joint4: -3.0718 # rad
                panda_joint5: -2.8973 # rad
                panda_joint6: -0.0175 # rad
                panda_joint7: -2.8973 # rad
            upper:
                panda_joint1: 2.8973 # rad
                panda_joint2: 1.7628 # rad
                panda_joint3: 2.8973 # rad
                panda_joint4: -0.0698 # rad
                panda_joint5: 2.8973 # rad
                panda_joint6: 3.7525 # rad
                panda_joint7: 2.8973 # rad

        joint_effort_limit:
            panda_joint1: 87 # Nm
            panda_joint2: 87 # Nm
            panda_joint3: 87 # Nm
            panda_joint4: 87 # Nm
            panda_joint5: 12 # Nm
            panda_joint6: 12 # Nm
            panda_joint7: 12 # Nm      

    realtime_config: enforce
    # Configure the initial defaults for the collision behavior reflexes.
    collision_config:
        lower_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
        upper_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
        lower_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
        upper_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
        # lower_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
        # upper_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
        # lower_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
        # upper_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]      
        # lower_torque_thresholds_acceleration: [10.0, 10.0, 9.0, 9.0, 8.0, 7.0, 6.0]  # [Nm] #HALVED ALL COLLISION THRESHOLDS
        # upper_torque_thresholds_acceleration: [10.0, 10.0, 9.0, 9.0, 8.0, 7.0, 6.0]  # [Nm]
        # lower_torque_thresholds_nominal: [10.0, 10.0, 9.0, 9.0, 8.0, 7.0, 6.0]  # [Nm]
        # upper_torque_thresholds_nominal: [10.0, 10.0, 9.0, 9.0, 8.0, 7.0, 6.0]  # [Nm]
        # lower_force_thresholds_acceleration: [10.0, 10.0, 10.0, 12.5, 12.5, 12.5]  # [N, N, N, Nm, Nm, Nm]
        # upper_force_thresholds_acceleration: [10.0, 10.0, 10.0, 12.5, 12.5, 12.5]  # [N, N, N, Nm, Nm, Nm]
        # lower_force_thresholds_nominal: [10.0, 10.0, 10.0, 12.5, 12.5, 12.5]  # [N, N, N, Nm, Nm, Nm]
        # upper_force_thresholds_nominal: [10.0, 10.0, 10.0, 12.5, 12.5, 12.5]  # [N, N, N, Nm, Nm, Nm] 
        lower_force_thresholds_acceleration: [40.0, 40.0, 40.0, 50.0, 50.0, 50.0]  # [N, N, N, Nm, Nm, Nm]
        upper_force_thresholds_acceleration: [40.0, 40.0, 40.0, 50.0, 50.0, 50.0]  # [N, N, N, Nm, Nm, Nm]
        lower_force_thresholds_nominal: [40.0, 40.0, 40.0, 50.0, 50.0, 50.0]  # [N, N, N, Nm, Nm, Nm]
        upper_force_thresholds_nominal: [40.0, 40.0, 40.0, 50.0, 50.0, 50.0]  # [N, N, N, Nm, Nm, Nm]      
  
gripper_config:
  joint_names:
    - panda_finger_joint1
    - panda_finger_joint2
  default_speed: 0.1  # [m/s]
  default_grasp_epsilon:
    inner: 0.005 # [m]
    outer: 0.005 # [m]

controllers_config:
    position_controller: "franka_ros_interface/position_joint_position_controller"
    torque_controller: "franka_ros_interface/effort_joint_torque_controller"
    impedance_controller: "franka_ros_interface/effort_joint_impedance_controller"
    velocity_controller: "franka_ros_interface/velocity_joint_velocity_controller"
    trajectory_controller: "position_joint_trajectory_controller"
    default_controller: "position_joint_trajectory_controller" # for safety, always set a position controller as default
    command_timeout: 0.2 # timeout to wait for consecutive torque control commands (or velocity) when using torque (or velocity) control. If timeout is violated, the controller interface will automatically switch to default controller for safety
    # additions
    cartesian_impedance_controller: "franka_ros_interface/cartesian_impedance_controller"
    cartesian_force_controller: "franka_ros_interface/cartesian_force_controller"
